In [ ]:
# LAB 1: Welcome to Machine Learning
# Student name: Eva
# Student ID: 20245103060

print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.

In [ ]:
import numpy as np

np.random.seed(42)

marks = np.array([55, 72, 48, 90, 66, 81])

print('Marks:', marks)
print('Passed:', marks[marks >= 50])

print('Minimum:', marks.min())
print('Standard Deviation:', marks.std())

bonus_marks = marks + 5
print('Bonus Marks:', bonus_marks)
print('Original Marks:', marks)

print('Number of Passed Students:', np.sum(marks >= 50))


matrix = marks.reshape(2, 3)
print('2 × 3 Matrix:')
print(matrix)

Marks: [55 72 48 90 66 81]
Passed: [55 72 90 66 81]
Minimum: 48
Standard Deviation: 14.372040758206733
Bonus Marks: [60 77 53 95 71 86]
Original Marks: [55 72 48 90 66 81]
Number of Passed Students: 5
2 × 3 Matrix:
[[55 72 48]
 [90 66 81]]

In [ ]:
import pandas as pd

data = {
    'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
    'study_hours': [2, 5, 1, 7, 3, 6],
    'sleep_hours': [8, 6, 9, 5, 7, 6],
    'attendance': [70, 88, 55, 95, 75, 91],
    'snacks': [3, 2, 5, 1, 4, 2],
    'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

features = ['study_hours', 'sleep_hours', 'attendance', 'snacks']
label = 'passed'

print("\nFeatures:", features)
print("Label:", label)

print("\nNumber of samples:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nStudents with attendance at least 80:")
display(df[df['attendance'] >= 80])

average_study = df[df['passed'] == 'Yes']['study_hours'].mean()

print("\n19. Average study hours of passed students:", average_study)

print("\n20. DataFrame sorted by attendance:")
display(df.sort_values(by='attendance', ascending=False))

Original DataFrame:

  student  study_hours  sleep_hours  attendance  snacks passed
0    Asha            2            8          70       3    Yes
1    Babu            5            6          88       2    Yes
2  Chayan            1            9          55       5     No
3    Dipa            7            5          95       1    Yes
4    Emon            3            7          75       4     No
5   Farah            6            6          91       2    Yes

16. Features: ['study_hours', 'sleep_hours', 'attendance', 'snacks']
Label: passed

17. Number of samples: 6
Number of columns: 6

18. Students with attendance at least 80:

  student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes

19. Average study hours of passed students: 5.0

20. DataFrame sorted by attendance:

  student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No

In [ ]:
import random
import numpy as np

def generate_scores(use_seed):
    if use_seed:
        random.seed(42)
        np.random.seed(42)

    return np.random.randint(40, 101, size=5)


print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))

print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]

In [1]:
import random
import numpy as np
def generate_scores(use_seed):
    if use_seed:
      random.seed(42)
      np.random.seed(42)
    return np.random.randint(40, 101, size=5)
print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))
print('The seed problem in machine learning occurs because random processes such as splitting data into training and testing sets,')
print('can produce different results each time. If we use a fixed random seed,such as 42, the same random results are generated every time,making the experiment reproducible.')
print('Without a seed,different runs may produce different results and accuracy scores.')
print('Therefore,using the same seed helps researchers compare models fairly and ensures that their results can be repeated.')

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]
The seed problem in machine learning occurs because random processes such as splitting data into training and testing sets,
can produce different results each time. If we use a fixed random seed,such as 42, the same random results are generated every time,making the experiment reproducible.
Without a seed,different runs may produce different results and accuracy scores.
Therefore,using the same seed helps researchers compare models fairly and ensures that their results can be repeated.